version: '3.8'

services:
  # Nokizaru Bot アプリケーション
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nokizaru-bot
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      # サーバー設定
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000

      # Slack設定
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}

      # データベース設定
      DATABASE_URL: ${DATABASE_URL}

      # ロギング
      RUST_LOG: ${RUST_LOG:-info,nokizaru_bot=debug}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nokizaru-network

  # PostgreSQL データベース（ローカル開発用）
  db:
    image: postgres:16-alpine
    container_name: nokizaru-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nokizaru}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nokizaru_password}
      POSTGRES_DB: ${POSTGRES_DB:-nokizaru}
    ports:
      - "${POSTGRES_PORT:-5532}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./apps/bot/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nokizaru}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - nokizaru-network

volumes:
  postgres-data:
    driver: local

networks:
  nokizaru-network:
    driver: bridge
